### ISSUE TITLE
How do I run the project?

### ISSUE THREAD

**Issue by tazeps** [pojana/sankaku_complex_downloader#1]
I installed Python3 and downloaded the project into my computer.

However I'm not sure where I should go to run the project or use the command line you indicated "py down_complex *etc*"
I tried using it in the python command lines interface but I only get a syntax error

I'd appreciate a more detailed outline on how to use the tool as I am inexperienced with running python tools

**Comment by pojana** [comment]
ok! 

I description how to use this project, Please try it
my project use windows, I not try on mac os and linux

first : check your download program source (down_cpomplex_APIv3.py)
     If first use, My project necessary Edit 「down_cpomplex_APIv3.py」
　 if your information that
　　　sankaku complex use id       -> pojana
　　　sankaku complex password -> password
　　　
　　　1. line: 26  USER = '' -> USER = 'pojana'
　　　2. line: 27  PASS = ''  -> PASS = 'password'
　　　3. save file about there edit
　 
　there Edit  that 1-3 finish, first step is done
   ** this step on readme : https://github.com/pojana/sankaku_complex_downloader#before-use

second: install python
     1. install your computer python3 (I use version 3.9)
     2. launch cmd [control + r  -> cmd -> enter
     3. on cmd type [py] and enter -> if launch python insall is success
     4. on cmd type [pip install requests] -> on cmd show [insatll successfully] -> OK

third: test download one posts from sankaku_beta
     1. launch cmd : key [control + r]  -> type [cmd] -> enter
     2. check project directory on your computer (example : C:\sankaku_complex_downloader-main ) 
     3. on cmd type [cd *projcet directory*] and enter (example : [cd C:\sankaku_complex_downloader-main)
     4. on cmd type [py down_cpomplex_APIv3.py https://beta.sankakucomplex.com/post/show/29017806] and enter
     5. on [download] folder in project directory on your computer -> if created and downloaded image, good!
     6. if download images in tag -> on cmd [py down_cpomplex_APIv3.py tag:*tag*] -> download images in [download] folder 
     7.  -> 6. step example [py down_cpomplex_APIv3.py tag:yaye] -> [yaye] tag image all download
******* Please ********
sry, 
While I creating this text i found same bugs, so I changed [down_cpomplex_APIv3.py]
so, if you try there steps on this, please re download this project 

if cause error on these steps, please error text
thank you!

**Comment by tazeps** [comment]
Thank you for replying!

I tried read me steps before and now I tried these steps. I still have a problem.
I redownloaded the project and tried your new steps but I dont get successfull message.

> "4. on cmd type [pip install requests] -> on cmd show [insatll successfully] -> OK"

I get this message


>>> pip install requests
  File "<stdin>", line 1
    pip install requests
        ^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?


I try to continue steps anyway, everything ok but when I try to do 

> "4. on cmd type [py down_cpomplex_APIv3.py https://beta.sankakucomplex.com/post/show/29017806] and enter"

I get this error

> 
>     import requests
> ModuleNotFoundError: No module named 'requests'
> 
> _directory_\sankaku_complex_downloader-main>
> 

I think my problem I don't know how to install pip library ? 
I try to follow the steps in this page to install pip library but i can't succeed.
https://pypi.org/project/pip/
it says python 3.10 form official website already comes with it.


Thank you for trying to help!

**Comment by pojana** [comment]
ok!

May be [pip install requests] command executed ​on python interpreter

On cmd, type [py] and enter, start python interpreter and show [>>>] on each lines
but, not work pip on python interpreter 
way to quit python interpreter, re start cmd, or type [quit()] command on python interpreter 

So, please re start cmd or quit() and try [pip install requests] 

sample image
![スクリーンショット 2021-11-10 033306](https://user-images.githubusercontent.com/93401637/140984873-e9e9c1dd-a8f1-469c-a2e0-5c386eb2a8b9.jpg)

thank you

**Comment by tazeps** [comment]
Yes I tried this before. I tried again. still same problem.
![image](https://user-images.githubusercontent.com/33405597/141657542-b8ff703b-567e-47c2-b985-1e999a627917.png)

**Comment by tazeps** [comment]
Yes I tried this before. same problem
![image](https://user-images.githubusercontent.com/33405597/141657597-4f076886-e1d8-472c-b067-5c3913e2c111.png)

**Comment by pojana** [comment]
ok!

May be not call pip from cmd.

So, please try it on cmd [ py -m pip install requests ]

Thank you!

**Comment by tazeps** [comment]
This one worked thank you so much!! ^^

now I can download by tag :D 

there is no way to make it search for pictures that contain 2 tags right ? instead of 1 tag.
like:
big_breasts+black_hair

**Comment by pojana** [comment]
I'm happy you used this project :D

OK! you can use multiple tags on this project,
when you search multiple tags, please put a space between tags.

For example :
  big_breasts+black_hair   -> big_breasts black_hair
  
  original+high_resolution+solo -> original high_resolution solo

Tnahk you!

**Comment by tazeps** [comment]
wonderful! Thank you so much! ^^/
